version: "1.0.0"

name: "experiment"

services: 
  app:
    build: .
    ports: 
      -  "3000:3000"
    networks:
      - backend
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=pass
    depends_on:
      - db

  db:
    image: postgres
    ports: 
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - vol1:/var/lib/postgresql/data    

volumes:
  vol1:

networks:
  backend: